// @ts-check
import { readFileSync } from 'node:fs';
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

/** Read a JSON file relative to this config, avoiding import-assertion syntax. */
const readJSON = (relativePath) =>
  JSON.parse(readFileSync(new URL(relativePath, import.meta.url), 'utf8'));

// The Runefile grammar the VS Code extension ships. Reusing it means the site's
// ```rune blocks and the editor highlight from one source.
const runeGrammar = readJSON('../editors/vscode/syntaxes/runefile.tmLanguage.json');

// Generated by `rune docs-site-gen` from docs/nav.yaml.
const sidebar = readJSON('./src/generated/sidebar.json');

const repo = 'https://github.com/rune-task-runner/rune';

export default defineConfig({
  site: 'https://rune-task-runner.github.io',
  base: '/rune',
  trailingSlash: 'always',
  outDir: './dist',
  integrations: [
    starlight({
      title: 'Rune',
      description: 'A shared task runner for humans and AI agents.',
      // The logo is an *imported* asset, so it must live under src/ — files in
      // public/ are served but not importable. favicon takes a served URL.
      logo: { src: './src/assets/icon.png', alt: 'Rune' },
      favicon: '/img/icon.png',
      social: [{ icon: 'github', label: 'GitHub', href: repo }],
      editLink: { baseUrl: `${repo}/edit/main/docs/` },
      lastUpdated: true,
      sidebar,
      expressiveCode: {
        // Starlight renders code through Expressive Code, so custom languages
        // are registered here — markdown.shikiConfig is not consulted.
        shiki: {
          // The spread MUST come first: the grammar file carries name
          // "Runefile", which would otherwise overwrite the fence language and
          // silently render every ```rune block as plain text.
          langs: [{ ...runeGrammar, name: 'rune', aliases: ['runefile'] }],
        },
      },
    }),
  ],
});
