// Package docsite transforms the canonical Markdown documentation under docs/
// into the content tree the Astro + Starlight site in website/ builds from.
//
// docs/**.md are the single source of truth and are never modified: this package
// only reads them. Everything it writes lives under website/ and is gitignored,
// regenerated by `rune docs-site-gen` (see cmd/docsite).
//
// The transform has three parts: frontmatter derived from each page's first
// heading and first prose paragraph (markdown.go), link rewriting from
// docs/-relative paths to site paths or GitHub blob URLs (links.go, slug.go),
// and the sidebar built from the docs/nav.yaml manifest (nav.go, sidebar.go).
package docsite
